name: Deploy Production
on:
  push:
    branches:
    - main

jobs:
  preview:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: jamesridgway/github-actions-approval-request@main
