name: CI
on:
  push:
    branches:
    - main

jobs:
  ci:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: jamesridgway/github-actions-approval-request@main
        with:
         trigger-workflow: 27506981
         notification-webhook-url: ${{ secrets.WEBHOOK_URL }}
