name: CI
on:
  push:
    branches:
    - main

jobs:
  ci:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3.2.0
        with:
          node-version: 14.x
      - run: npm install
      - run: npm test
      - uses: pulumi/actions@v3
        with:
          command: up
          stack-name: staging
        env:
          ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
          ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
      - uses: jamesridgway/github-actions-approval-request@main
        with:
         trigger-workflow: 27506981
         notification-webhook-url: ${{ secrets.WEBHOOK_URL }}
         github-actions-approval-api-url: ${{secrets.ACTIONS_APPROVAL_API_URL}} 
