name: Deploy Production
on:
  workflow_dispatch:
    inputs:
      commit:
        # Require the Commit ID as an input so that we deploy a specific commit
        type: string
        description: 'Commit ID to deploy'
        required: true
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      # Checkout source code at a specific commit
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.commit }}
      # Setup node
      - uses: actions/setup-node@v3.2.0
        with:
          node-version: 14.x
      # Install dependencies
      - run: npm install
      # Deploy to production
      - uses: pulumi/actions@v3
        with:
          command: up
          stack-name: production
        env:
          ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
          ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
